version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:current
    resource_class: medium

jobs:
  image:
    executor: base
    parameters:
      dockerfile:
        type: string
      repo-name:
        type: string
        default: myimage
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: |
          docker image build -t << parameters.repo-name >> -f << parameters.dockerfile >> .
      - run: |
          docker image ls
      - run: |
          docker container run --rm << parameters.repo-name >> bash -c "printenv BASH_ENV"

workflows:
  build:
    jobs:
      - image:
          matrix:
            parameters:
              dockerfile: 
                - Dockerfile-node-1616
                - Dockerfile-node-1617
